<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="1" tests="2" name="ParallelTestExecution" time="12.001" errors="0" timestamp="2025-08-14T14:30:48 IST">
  <testcase classname="Testing_package.TestClass1" name="amazon" time="9.285"/>
  <testcase classname="Testing_package.TestClass2" name="amazon" time="11.929">
    <failure type="java.lang.AssertionError" message="flipkart URL validation failed expected [https://www.flipkart.in/] but found [https://www.flipkart.com/]">
      <![CDATA[java.lang.AssertionError: flipkart URL validation failed expected [https://www.flipkart.in/] but found [https://www.flipkart.com/]
at Testing_package.TestClass2.amazon(TestClass2.java:29)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- amazon -->
</testsuite> <!-- ParallelTestExecution -->
